# Generated by Django 6.0.2 on 2026-02-23 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author_alter_book_description_and_more'),
        ('reading', '0002_rename_current_page_readingprogress_last_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image_url', models.URLField(max_length=2048)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='books.book')),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'page_number'], name='reading_boo_book_id_9944a4_idx')],
                'unique_together': {('book', 'page_number')},
            },
        ),
    ]
