# Generated by Django 6.0.2 on 2026-02-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_bookpageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpageimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bookpageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
    ]
